#ifndef __SQL_CONST__
#define __SQL_CONST__

#define SQL_TABLE_NAME_MAX_SIZE 64
#define SQL_COLUMN_NAME_MAX_SIZE 64
#define SQL_MAX_COLUMNS_SUPPORTED_PER_TABLE 32
#define SQL_BTREE_MAX_CHILDREN_CATALOG_TABLE 4
#define SQL_BTREE_MAX_CHILDREN_SCHEMA_TABLE 4
#define SQL_BTREE_MAX_CHILDREN_RDBMS_TABLE 4
#define SQL_MAX_PRIMARY_KEYS_SUPPORTED  SQL_MAX_COLUMNS_SUPPORTED_PER_TABLE
#define SQL_MAX_GROUP_BY_N_SUPPORTED    3
#define SQL_OPERAND_MAX_VALUE   256
#define SQL_ALIAS_NAME_LEN  32
#define SQL_MAX_JOIN_TABLES_SUPPORTED   3
#define SQL_MAX_AGG_FN_NAME_LEN 8
#define SQL_MAX_WHERE_LITERAL_ARRAY_SIZE    128
#define SQL_MAX_DELETE_ACCUMULARE_COUNT 500
#define SQL_MAX_COLS_IN_SELECT_LIST 16
#define SQL_MAX_COLS_IN_GROUPBY_LIST    16
#define SQL_MAX_TABLES_IN_JOIN_LIST 8
#define SQL_COMPOSITE_COLUMN_NAME_SIZE  \
    (SQL_TABLE_NAME_MAX_SIZE + SQL_COLUMN_NAME_MAX_SIZE + SQL_MAX_AGG_FN_NAME_LEN + 2)

#endif 