#ifndef __SQL_CONST__
#define __SQL_CONST__

#define SQL_TABLE_NAME_MAX_SIZE 64
#define SQL_COLUMN_NAME_MAX_SIZE 64
#define SQL_MAX_COLUMNS_SUPPORTED_PER_TABLE 32
#define SQL_BTREE_MAX_CHILDREN_SCHEMA_TABLE 4
#define SQL_BTREE_MAX_CHILDREN_RDBMS_TABLE 4
#define SQL_BTREE_MAX_CHILDREN_CATALOG_TABLE 4
#define SQL_STRING_MAX_VALUE_LEN   256

#endif 